/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-container": "#fffbff",
        "tertiary": "#00685c",
        "secondary-container": "#ff85a2",
        "outline-variant": "#c9c4d5",
        "inverse-primary": "#c7bfff",
        "on-tertiary-fixed": "#00201b",
        "surface-container-low": "#f7f1ff",
        "on-background": "#1d163a",
        "tertiary-fixed-dim": "#4ddcc6",
        "primary-container": "#7262dd",
        "surface-tint": "#5b4bc5",
        "secondary-fixed": "#ffd9df",
        "primary-fixed-dim": "#c7bfff",
        "secondary": "#a03a57",
        "inverse-on-surface": "#f4eeff",
        "tertiary-fixed": "#6ef9e2",
        "surface": "#fdf8ff",
        "on-primary-fixed-variant": "#4330ac",
        "surface-container-high": "#ece4ff",
        "surface-dim": "#ded4ff",
        "surface-bright": "#fdf8ff",
        "secondary-fixed-dim": "#ffb1c1",
        "background": "#fdf8ff",
        "on-error": "#ffffff",
        "primary": "#5948c2",
        "on-tertiary": "#ffffff",
        "on-surface": "#1d163a",
        "error": "#ba1a1a",
        "on-surface-variant": "#474553",
        "inverse-surface": "#322b50",
        "error-container": "#ffdad6",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed-variant": "#005047",
        "on-secondary-fixed-variant": "#812240",
        "on-error-container": "#93000a",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#e5deff",
        "surface-container-highest": "#e6deff",
        "on-tertiary-container": "#f4fffb",
        "on-secondary-container": "#781b39",
        "tertiary-container": "#008374",
        "on-primary-fixed": "#180065",
        "surface-variant": "#e6deff",
        "on-primary": "#ffffff",
        "surface-container": "#f2ebff",
        "outline": "#787585",
        "on-secondary-fixed": "#3f0017"
      },
      borderRadius: { "DEFAULT": "1rem", "lg": "2rem", "xl": "3rem", "full": "9999px" }
    }
  },
  plugins: [],
}
